### PR TITLE
redesigned layout

### PR DESCRIPTION
**Pull request by vinaypuppal**
@duttakapil requested to push these changes here.

Demo: https://fcc.now.sh

> Note: Licence and Readme are taken from fcc-hyd/fcc-hyd.git.io Repo

### CODE REVIEW

**Comment by vramana** [comment]
Can you change yarn.lock to be recognised as binary in gitattributes?

**Comment by vramana** [comment]
Why are we adding this here? Instead of just starting everything from scratch?

**Comment by vinaypuppal** [comment]
@vramana Its seems `yarn.lock` should not be treated as binary file in git according to this answer here http://stackoverflow.com/questions/40532940/should-yarn-lock-be-treated-as-a-binary-file-in-git 
Is this what you asked??

**Comment by vramana** [comment]
Okay. I just tried to avoid large yarn diffs in my projects. Either way works.

**Comment by duttakapil** [comment]
@vramana this is starting everything from scratch. This repo is where we'll contain the code for the new website, and this interface by @vinaypuppal is what we're gonna use for now. 

@vinaypuppal everything looks good. 

Discuss : should we have a gh-pages branch to temporarily host this project on fcc-hyd.github.io/fcc-hyd?

**Comment by vinaypuppal** [comment]
> Discuss : should we have a gh-pages branch to temporarily host this project on fcc-hyd.github.io/fcc-hyd?

@duttakapil After merging,If required i can setup `gh-pages` branch with only built files similar to  `survey` repo.

**Comment by duttakapil** [comment]
@vinaypuppal ya, go ahead with that. I'll merge this

**Comment by vramana** [comment]
image

I have to strain my eyes to read the font here. Can we this be changed?

**Comment by duttakapil** [comment]
Ok another Q, we obviously have to make some changes to this interface, add content as well. Should we do that after merge? I think that would be better

**Comment by vramana** [comment]
I don't mind merging and doing it later. But I don't understand at all how that would be better.

**Comment by vinaypuppal** [comment]
As i commented in #1 just now, if we want to use React.js , then this PR is useless.
If we want to go with vanilla JS then merge this PR

**Comment by vramana** [comment]
I honestly feel this should be scrapped and use next.js to build everything.

**Comment by vinaypuppal** [comment]
@vramana okay fine then I am closing this PR

**Pull request closed without merging**
